---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: posts
  label: Posts
- type: heading
  label: Kyroxen
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/media"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: "/site"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
